### ISSUE TITLE
Small bug fix

### ISSUE THREAD

**Issue by Anmol6** [dalgu90/resnet-18-tensorflow#1]
Hey,

Thanks for your code. It looks like there's a small bug in the '_bn' function of utils.py. When you call '_bn' in other parts of your code (eg. in the residual_block function of resnet.py) you are passing the scope name as the third argument, whereas the global_step is the third argument in _bn. I would suggest switching the order of the global_step and name arguments and not setting any default value for the name argument in _bn.

**Comment by dalgu90** [comment]
It seems no problem. Note that the global step and name arguments of `_bn` function are properly passed either by the named arguments or with the correct argument positions. And also, please note that there are two functions named `_bn` and the function `_bn` in the `util` module only called by a member function `_bn` in the `ResNet`(see `resnet.py`).

Thank you for your concern about the code. :)
