### ISSUE TITLE
How to make a data set？

### ISSUE THREAD

**Issue by nirvus** [dalgu90/resnet-18-tensorflow#3]
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("train_image/DecodeCSV:0", shape=(), dtype=float32, device=/device:CPU:0)'

**Comment by dalgu90** [comment]
Sorry for late reply.

I guess you don't have the ImageNet 1K dataset, and you can download [ImageNet](http://image-net.org/download) site(you need to sign up to download the dataset).
Note that in the original ImageNet dataset, not all image files are valid JPEG files. See [this gist](https://gist.github.com/dalgu90/fc358fdde0a7fe6fbbe0254b901a0de3).
